### ISSUE TITLE
Drift

### ISSUE THREAD

**Issue by brhea** [juchong/ADIS16470-RoboRIO-Driver#10]
Our team measures from 7 to 8.5 degrees of drift in 2.5 minutes. This seems high as compared to the spec on the chip. We tried multiple calibration times up to 16 sec with similar results. We ran this test on two separate chips on two different dev boards. Boards were perfectly still during calibration.

What is a reasonable drift for the driver with this chip. How much drift did you see when testing your calibration method. 

Our team uses Java.

**Comment by brhea** [comment]
I added our own calibrate routine that follows yours... It waits for about 5 seconds after the roborio boots, then zeros the gyro and waits 4 seconds (that's 200 loops of the rio code because it runs every 20 ms). I then divided the gyro reading by 200 and saved that number away (bias increment). This is our own calibration bias.... we rezero the gyro after calculating this and then increment a bias by the bias increment we calculated every 20 ms. This number is subtracted from the gyro value every time we read it.

We basically did our own calibration in a very similar way to what you do. This reduced our gyro drift from 7 to 8.5 degrees in 2.5 minutes to only 0.12 degrees in 2.5 minutes. Gyro seems to also provide good readings .... we've just offset the drift.

There may be some error in the driver. We basically performed the same type of offset calibration that you are doing. We just followed up yours with our own and at least initially it looks like we have great results.

**Comment by nbgray** [comment]
Team 1745 saw a huge amount of drift - ~.15 degrees per second!

I mostly made it better by writing our own calibrate method to determine how much drift was occurring and subtracting it out:


    public void gyroCalibrate(){
        startTime = Timer.getFPGATimestamp();        
        double startAngle = imu.getAngle();

        try{
            Thread.sleep(16000);
        }catch(Exception e)
        {
            //dont care about exceptions rn
        }

        driftPerSecond = (imu.getAngle() - startAngle)/(Timer.getFPGATimestamp() - startTime);
    }

    public void resetGyroAngle(){
        imu.reset();
        startTime = Timer.getFPGATimestamp();
    }

    //Angle does not reset to 0 after full rotation - goes to 361...2... etc
    public double getGyroAngle(){
        double runTime = Timer.getFPGATimestamp() - startTime;
        double drift = runTime * driftPerSecond;
        return imu.getAngle() - drift;
    }

**Comment by juchong** [comment]
@nbgray @brhea The drift compensation (bias estimation) algorithm built into the IMU hardware does essentially the same thing your code is achieving, only without the added CPU overhead. I recommend setting `ConfigCalTime()` to `_8s` or `_16s` for best performance. Be sure to call `Calibrate()` after waiting to use the latest estimate.

**Comment by brhea** [comment]
Test of reopen

**Comment by brhea** [comment]
Just verifying issue reopen works
