### ISSUE TITLE
X and Y axis positions

### ISSUE THREAD

**Issue by brhea** [juchong/ADIS16470-RoboRIO-Driver#11]
You've provided a complimentary filter for the X and Y axis angles. I've not been able to find a method to read the X and Y angles in a similar way to the Z angle which is integrated.

The Z angle provides a very reliable reading that is repeatable and consistent.

The X and Y complimentary values seem to be ok until we run our shooter. Perhaps it's vibration but these values rapidly increase from near 0 to 12+ degrees in just a few seconds when we start our shooter. When we stop the shooter it coasts down and the X/Y values ramp back to near 0. 

The Z axis or getAngle() value remains relatively constant around zero when running our shooter. 

The X/Y axis measurement is critical for things like climbing level or determining when your bot is on top of a ball in autonomous. 

Could you add an X and Y totalized angle without the complimentary filter?

**Comment by juchong** [comment]
@brhea Hi! The complementary filter outputs provided by the driver fuse gyroscope and accelerometer data to produce a very stable angle measurement with respect to gravity. This sensor fusion is what keeps each of the sensors from drifting over time, but as you've experienced, it also allows error (vibration through the accelerometers) to bleed into the angle estimate. 

Even though it'll be impossible to completely tune out the shooter's influence in the measurement, you might be able to improve performance by adjusting the `m_tau` value in `ADIS16470.h`. Take a look at this (link)[https://sites.google.com/site/myimuestimationexperience/filters/complementary-filter] for guidance on tuning the sensor.
