### ISSUE TITLE
Gyro does not start when code boots

### ISSUE THREAD

**Issue by brhea** [juchong/ADIS16470-RoboRIO-Driver#12]
When we power our robot up, the gyro does not start. Messages are sent to the driver's station indicating that the calibration is in progress and then another indicating that calibration completed successfully. However, all values read from the gyro remain at exactly 0.

When we reboot the roborio from the driver's station, the gyro calibrates and starts up normally.

**Comment by juchong** [comment]
@brhea, A few teams identified an incompatibility between the IMU driver and the CTRE Phoenix libraries. I haven't been able to reproduce the issue, but others have suggested a potential fix. I believe (judging by the suggested fix) that a slightly increased delay during start-up is causing some of my start-up communication checks between the IMU and the RIO to fail. The update should be available in the Maven repository in a bit. I'll close this issue once I push the changes.

**Comment by juchong** [comment]
The C++ and Java changes have been pushed to the Maven repository. Please let me know if this solves the issue for you, too. If it doesn't, please re-open this issue so we can continue debugging!
