### ISSUE TITLE
Gyro Drift .. Refer to issue #10...

### ISSUE THREAD

**Issue by brhea** [juchong/ADIS16470-RoboRIO-Driver#13]
Here's a possible fix for the drift issue with the driver. You suggested increasing the calibration time and that really doesn't have any effect. The drift is far above the spec and makes the chip almost unusable.

First, let's assume that the chip and its firmware are good. Then the problem has to be in the driver. Our team wrote our own calibration that runs after the chips calibration which yielded surprisingly good results. Our drifts with this change are in the 0.1 to 0.3 deg in 2.5 minutes (FRC match time) which is great. The drift is amazingly consistent and looks like your integrator is adding up a constant error over time. We also record the complimentary values at end of our calibration and tare them off.

I've read through your code and you are using the following constant in your integration:

  // Static Constants
  private static final double delta_angle_sf = 2160.0 / 2147483648.0;

Your integration looks like this.
          // Scale sensor data
          delta_angle = (toInt(buffer[i + 3], buffer[i + 4], buffer[i + 5], buffer[i + 6]) * delta_angle_sf) / (500.0 / (buffer[i] - previous_timestamp));

m_integ_angle += delta_angle;

You return the following:

  public synchronized double getAngle() {
    return m_integ_angle;
  }

If your scale factor

delta_angle_sf/500 is wrong by even a small amount, you are integrating error every time you take a sample. I'm not sure where the delta_angle_sf comes from... it looks kind of magic. I suppose there could even be round off error created there that's integrated.

What if rather than integrating this constant every scan, you just multiply the return value by it. That way you don't integrate any error in the factor (I suppose that first I'd also verify that this number is correct).

Consider trying: 

          delta_angle = (toInt(buffer[i + 3], buffer[i + 4], buffer[i + 5], buffer[i + 6])  * (buffer[i] - previous_timestamp));

  public synchronized double getAngle() {
    return m_integ_angle * delta_angle_sf / 500;
  }

This change only integrates the values read from the chip. Assuming they are correct, this has potential to remove at least some of the drift. 

I suppose the other source of error could be if the timestamps are wrong but you seem to be getting those from the chip? 

We also saw that the gyro reset function does not reset the complimentary x and y axis to 0 properly. We're always seeing 1 to 3 degrees of offset after calibration. We have just been storing that with our own calibration routine and taring it off. This works well for us.

Consider modifying your reset routine to the following:

  public void reset() {
    synchronized (this) {
      m_integ_angle = 0.0;
      compAngleX = 0;
      compAngleY = 0;
    }
  }

Note that for this to work... compAngleX and compAngleY must be made fields in order to reset them. There's no way to reset them from outside your acquire method.

Our team would still prefer to have an X and Y angle that does not have the sensor fusion. I appreciate that it is cool, academically interesting, etc. but on a robot it's not reliably usable due to vibration issues from mechanisms like shooters or proximity to motors that create magnetic fields. Z axis do not seem to be adversely affected by vibration.

We can use the complimentary values at the end of the game for climbing because we do not use our shooter at that time. However, during the autonomous portion of the game, we will not be able to use them to detect when our bot is on top of a ball and provide a safety stop.

**Comment by juchong** [comment]
@brhea The complementary outputs are always referenced to gravity, thus there is no way to "reset" them. When used in a leveling application, gravity is often the desired reference.

I **highly** suggest that you refer to the ADIS16470 datasheet located [here](https://www.analog.com/media/en/technical-documentation/data-sheets/ADIS16470.pdf). The integrated angle output is generated by accumulating the **32-bit delta angle register** provided by the part and is not generated by integrating the raw outputs, as you suggested above. The formula provided on page 21 of the datasheet shows the equation required to generate a heading estimate. I've provided the pertinent excerpt below. 
![image](https://user-images.githubusercontent.com/342107/75050171-7baebc80-5499-11ea-9771-d6ca73d2f31f.png)

The "magic" constant you're referring to is the scale factor used for 32-bit delta angle registers. 
![image](https://user-images.githubusercontent.com/342107/75050387-e233da80-5499-11ea-8519-e4b228ad59d8.png)

Once again, I **highly** suggest you take a look through the datasheet, and if you have any questions, please feel free to reach out. As I stated in one of the other issues you've submitted, many teams seem to be enjoying the sensor's excellent performance. I suspect that your troubles are centered around your robot code you've written more so than the driver I've provided.
