### ISSUE TITLE
Gyroscope Data Light does not turn on

### ISSUE THREAD

**Issue by PCModeActivate** [juchong/ADIS16470-RoboRIO-Driver#2]
We encountered a number of issues when configuring our ADIS 16470. We used roborio image 2019 v14, and WPILib 2019.4.1. We used the sample java code, and a few issues came out: the data light is never on, even after calibration; the checksum is incorrect (invalid, does not match); dt drops to 0 after spewing out valid data for a few seconds (when we made the checksum condition always true, such that it will always output regardless of checksum validity).
[Chief Delphi Question Link](https://www.chiefdelphi.com/t/adis-16470/358989)
-- Team 6866

**Comment by PCModeActivate** [comment]
P.S. we have worked on the Gyro since the beginning of the build season and it still doesn't work, even after WPILib update 3.2. @balaji-venkatesh

**Comment by PCModeActivate** [comment]
P.S.: We have been working on it since the beginning of the build season. We have encountered a number of issues. It still doesn't work, even after WPILib 3.2 update. @balaji-venkatesh

**Comment by juchong** [comment]
@PCModeActivate This has been resolved in the 2020 version of the driver.
